# Superagent Status Page Configuration
owner: superagent-dev
repo: status
user-agent: superagent-dev

sites:
  - name: Atender App
    url: https://app.atender.com
  - name: Atender GraphQL API
    url: https://app.atender.com/graphql
    method: POST
    headers:
      - "Content-Type: application/json"
    body: '{"query":"{ __typename }"}'

status-website:
  cname: status.atender.com
  logoUrl: https://raw.githubusercontent.com/superagent-dev/status/master/assets/upptime-icon.svg
  name: Superagent Status
  theme: dark
  introTitle: "**Superagent** Status Page"
  introMessage: This status page provides real-time monitoring of our services. Powered by [Upptime](https://github.com/upptime/upptime).
  navbar:
    - title: Status
      href: /
    - title: Atender
      href: https://app.atender.com

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
